name: Validate Turtle file
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install jena
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get -y install libapache-jena-java
      - name: Validate Turtle file
        run: turtle edpop-record-ontology.ttl
